---
kind: pipeline
name: build

steps:
- name: run tests
  image: golang
  commands:
  - sleep 5
  - make dep
  - make test
  environment:
    MYSQL_TEST: true
    MYSQL_TEST_HOST: mysql-server
    MYSQL_TEST_USER: root

services:
- name: mysql-server
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_DATABASE: certs
  ports:
  - 3306
