language: go
services:
  - mysql

env:
  - MYSQL_TEST="true"

go:
  - 1.11.x
  - 1.10.x
  - 1.9.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - make dep
  - mysql -e 'CREATE DATABASE certs;'

install:
  - go version

sudo: false
script:
  - make test
