language: go
services:
  - mysql

# env:
#   - SUITE=lint
#   - SUITE=test

matrix:
  fast_finish: true
  allow_failures:
    - go: master
  include:
  - go: "1.11.x"
    script: GO111MODULE="on" MYSQL_TEST="true" make test flags="-mod=vendor"
  - go: "master"
    script: GO111MODULE="on" MYSQL_TEST="true" make test flags="-mod=vendor"
  - go: "1.10.x"
    script: MYSQL_TEST="true" make test
  - go: "1.9.x"
    script: MYSQL_TEST="true" make test

notifications:
  email: false

before_install:
  - mysql -e 'CREATE DATABASE certs;'

install:
  - go version

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
