language: go
services:
  - mysql

env:
  - MYSQL_TEST="true"

go:
  - 1.10.3
  - 1.9.7
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - make dep

install:
  - go version

before_script:
  - mysql < db/seed.sql

sudo: false
script:
  - make test